on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10m'
      - uses: actions/checkout@master
      - name: 1
        env:
          UPDATE_1: ${{ secrets.UPDATE_1 }}
        run: |
          wget ${{ secrets.UPDATE_1 }}